// sonic06demo - ReXGlue Recompiled Project
// Generated by: rexglue init
//
// This file is SDK-managed. Customizations go in virtual hook overrides.
// Running 'rexglue migrate' will overwrite this file.

#include "generated/sonic06demo_config.h"
#include "generated/sonic06demo_init.h"

#include <rex/rex_app.h>
#include <rex/graphics/vulkan/graphics_system.h>

class Sonic06demoApp : public rex::ReXApp {
 public:
  using rex::ReXApp::ReXApp;

  static std::unique_ptr<rex::ui::WindowedApp> Create(
      rex::ui::WindowedAppContext& ctx) {
    return std::unique_ptr<Sonic06demoApp>(new Sonic06demoApp(ctx, "sonic06demo",
        {PPC_CODE_BASE, PPC_CODE_SIZE, PPC_IMAGE_BASE,
         PPC_IMAGE_SIZE, PPCFuncMappings}));
  }
};

REX_DEFINE_APP(sonic06demo, Sonic06demoApp::Create)
